flight_controller/components/lora_com/CMakeLists.txt:
	cd ../flight_controller/components; ln -sf ../../shared_components/lora_com .

base_station/components/lora_com/CMakeLists.txt:
	cd ../base_station/components; ln -sf ../../shared_components/lora_com .

flight_controller/components/esp32-lora-library/CMakeLists.txt:
	cd ../flight_controller/components; ln -sf ../../shared_components/esp32-lora-library .

base_station/components/esp32-lora-library/CMakeLists.txt:
	cd ../base_station/components; ln -sf ../../shared_components/esp32-lora-library .

create_symlinks: flight_controller/components/lora_com base_station/components/lora_com \
	flight_controller/components/esp32-lora-library base_station/components/esp32-lora-library
