stages:
  - docs

readme_pdf:
  stage: docs
  image: debian:bookworm-slim
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends -qq make pandoc texlive-latex-recommended texlive-fonts-recommended texlive-lang-german texlive-latex-extra lmodern
  script:
    - make export_documentation
  artifacts:
    paths:
      - README.pdf
    expire_in: 1 week
