stages:
  - docs

readme_pdf:
  stage: docs
  image: pandoc/extra:latest
  before_script:
    - apk add --no-cache make
  script:
    - make readme_pdf
  artifacts:
    paths:
      - README.pdf
    expire_in: 1 week
