// Auto-generated by fire_detection_training/export_c_array.py -- do not edit by hand.
#pragma once

extern const unsigned char g_model_data[];
extern const unsigned int g_model_data_len;

extern const char *const g_model_labels[];
extern const unsigned int g_model_labels_len;
