"""Embed the quantized .tflite model into the ESP-IDF project as a C++ array.

Writes main/model_data.cpp and main/model_data.hpp into fire_detection_esp/,
replacing the placeholder committed there. Run this after convert_to_tflite.py
and before building fire_detection_esp.
"""

import argparse
from pathlib import Path

from config import ESP_MAIN_DIR, LABELS_PATH, MODEL_TFLITE_PATH

HEADER_TEMPLATE = """\
// Auto-generated by fire_detection_training/export_c_array.py -- do not edit by hand.
#pragma once

extern const unsigned char g_model_data[];
extern const unsigned int g_model_data_len;

extern const char *const g_model_labels[];
extern const unsigned int g_model_labels_len;
"""

SOURCE_HEADER_TEMPLATE = """\
// Auto-generated by fire_detection_training/export_c_array.py -- do not edit by hand.
#include "model_data.hpp"

alignas(8) const unsigned char g_model_data[] = {{
{bytes}
}};
const unsigned int g_model_data_len = {length};

const char *const g_model_labels[] = {{
{labels}
}};
const unsigned int g_model_labels_len = {num_labels};
"""


def format_bytes(data: bytes, columns: int = 12) -> str:
    lines = []
    for i in range(0, len(data), columns):
        chunk = data[i : i + columns]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=MODEL_TFLITE_PATH)
    parser.add_argument("--labels", type=Path, default=LABELS_PATH)
    parser.add_argument("--output-dir", type=Path, default=ESP_MAIN_DIR)
    args = parser.parse_args()

    if not args.model.is_file():
        raise SystemExit(f"{args.model} not found -- run convert_to_tflite.py first.")
    if not args.labels.is_file():
        raise SystemExit(f"{args.labels} not found -- run train.py first.")
    if not args.output_dir.is_dir():
        raise SystemExit(f"{args.output_dir} not found -- is fire_detection_esp/main/ present?")

    model_bytes = args.model.read_bytes()
    labels = [line.strip() for line in args.labels.read_text().splitlines() if line.strip()]

    header_path = args.output_dir / "model_data.hpp"
    source_path = args.output_dir / "model_data.cpp"

    header_path.write_text(HEADER_TEMPLATE)
    source_path.write_text(
        SOURCE_HEADER_TEMPLATE.format(
            bytes=format_bytes(model_bytes),
            length=len(model_bytes),
            labels="\n".join(f'    "{label}",' for label in labels),
            num_labels=len(labels),
        )
    )

    print(f"Wrote {header_path}")
    print(f"Wrote {source_path} ({len(model_bytes) / 1024:.1f} KB model, {len(labels)} labels: {labels})")


if __name__ == "__main__":
    main()
